# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ed0c080ce2ea8247aa9f479101e4e4f2713c1a70dbc7033ee5aebd56558d0ca8b761a120dd9dcb75dc5b3c48608468e2f512a6ca2b9083717023891f8636349

test:
  secret_key_base: 0d3c44f89c8d569323276d49b578dbc5528a12072ba57a2fd70db5ce0786595c98eb3b5b1062f708993f72ed439f902d5a8df6aee34b9cec81750457c2d6a352

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
